// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sonastea/ticketopia/views/components/icon"

// Keep product-facing names stable while the library owns the SVG vocabulary.
func Icon(name string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = icon.Icon(iconName(name))(icon.Props{Class: "icon", Attributes: templ.Attributes{"aria-hidden": "true", "focusable": "false"}}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func iconName(name string) string {
	switch name {
	case "discover":
		return "compass"
	case "saved":
		return "bookmark"
	case "community":
		return "messages-square"
	case "profile":
		return "user-round"
	case "interests":
		return "star"
	case "location":
		return "map-pin"
	case "filters":
		return "sliders-horizontal"
	case "arrow":
		return "arrow-right"
	case "back":
		return "arrow-left"
	case "external":
		return "external-link"
	case "chevron":
		return "chevron-down"
	case "close":
		return "x"
	default:
		return name
	}
}

var _ = templruntime.GeneratedTemplate
