-- Run as the local admin AFTER migrations. Repeatable and no runtime DDL.
GRANT INSERT, UPDATE ON ticketopia.events TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.event_providers TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.accounts TO 'ticketopia_runtime'@'%';
GRANT INSERT ON ticketopia.account_identities TO 'ticketopia_runtime'@'%';
GRANT INSERT, DELETE ON ticketopia.account_credentials TO 'ticketopia_runtime'@'%';
GRANT INSERT, DELETE ON ticketopia.auth_flows TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE, DELETE ON ticketopia.auth_rate_limits TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.event_snapshots TO 'ticketopia_runtime'@'%';
GRANT INSERT, DELETE ON ticketopia.saved_events TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE, DELETE ON ticketopia.event_interests TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE, DELETE ON ticketopia.event_recommendations TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.recommendation_feed_events TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.recommendation_activity TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.discussion_posts TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE, DELETE ON ticketopia.post_helpful TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.moderation_reports TO 'ticketopia_runtime'@'%';
GRANT INSERT ON ticketopia.moderation_decisions TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.moderation_appeals TO 'ticketopia_runtime'@'%';
-- account_roles and account_role_events retain SELECT-only runtime access.
GRANT INSERT, UPDATE ON ticketopia.artists TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.artist_providers TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.venues TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.venue_providers TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.event_history_state TO 'ticketopia_runtime'@'%';
GRANT INSERT ON ticketopia.event_observations TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.collection_tasks TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.collection_runs TO 'ticketopia_runtime'@'%';
GRANT INSERT ON ticketopia.collection_pages TO 'ticketopia_runtime'@'%';
GRANT INSERT ON ticketopia.collection_run_events TO 'ticketopia_runtime'@'%';
GRANT INSERT, UPDATE ON ticketopia.provider_budgets TO 'ticketopia_runtime'@'%';
GRANT INSERT, DELETE ON ticketopia.artist_follows TO 'ticketopia_runtime'@'%';
GRANT INSERT, DELETE ON ticketopia.venue_follows TO 'ticketopia_runtime'@'%';
