// Isolated production-handler/MariaDB fixtures. See docs/follows.md.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.FOLLOWS_BASE_URL;
const fallback = process.env.FOLLOWS_FALLBACK_URL;
const out = process.env.FOLLOWS_REVIEW_DIR || path.resolve(__dirname, '../.impeccable/review');
const report = { checks: [], accessibility: [], screenshots: [], consoleErrors: [] };
const check = (name, result) => { assert.ok(result, name); report.checks.push(name); };
fs.mkdirSync(out, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE });
  try {
    const owner = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await owner.addCookies([base, fallback].map(url => ({ name: 'ticketopia_session', value: process.env.FOLLOWS_SESSION, url })));
    const page = await owner.newPage();
    page.on('pageerror', error => report.consoleErrors.push(error.message));
    const collection = () => page.locator('ul[aria-label="Your follows"]');
    const results = () => page.locator('ul[aria-label="Search results"]');
    const api = async (method, target, body) => owner.request.fetch(base + target, {
      method, headers: { Authorization: 'Bearer ' + process.env.FOLLOWS_API_TOKEN }, data: body
    });
    const capture = async (name, width, enlarged = false) => {
      await page.setViewportSize({ width, height: 1000 });
      await page.evaluate(async enlarged => {
        document.documentElement.style.fontSize = enlarged ? '200%' : '';
        await document.fonts.ready;
      }, enlarged);
      check(name + ': no horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      check(name + ': action targets at least 44px', await page.locator('main button, main input:not([type="hidden"]), main select').evaluateAll(nodes => nodes.every(node => node.getBoundingClientRect().height >= 44)));
      await page.evaluate(() => scrollTo(0, 0));
      const file = path.join(out, 'follows-' + name + '.png');
      if (!process.env.FOLLOWS_SKIP_CAPTURE) await page.screenshot({ path: file, fullPage: true });
      report.screenshots.push(file);
      if (process.env.AXE_SCRIPT) {
        await page.addScriptTag({ path: process.env.AXE_SCRIPT });
        const scan = await page.evaluate(() => axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } }));
        report.accessibility.push({ name, violations: scan.violations.map(v => ({ id: v.id, impact: v.impact })) });
        check(name + ': axe clean', scan.violations.length === 0);
      }
    };
    await page.goto(base + '/follows');
    check('Honest empty state', await page.getByText('No follows on this page yet.', { exact: false }).isVisible());
    await page.getByLabel('Name', { exact: true }).fill('Private');
    await page.getByRole('button', { name: 'Search', exact: true }).click();
    check('Artist search', await results().locator('li').count() === 2);
    await results().getByRole('button', { name: 'Follow Private artist', exact: true }).click();
    check('Native Follow syncs result and collection', await collection().locator('li').count() === 1 && await results().getByRole('button', { name: 'Unfollow Private artist', exact: true }).isVisible());
    const list = await (await api('GET', '/api/v1/me/follows')).json();
    check('API sees browser follow', list.items.length === 1 && list.items[0].target.kind === 'artist');
    const repeated = await api('PUT', '/api/v1/me/follows/artist/ticketmaster:Follow_0');
    check('API retry preserves timestamp', repeated.status() === 200 && (await repeated.json()).followed_at === list.items[0].followed_at);
    await page.getByLabel(/^Search for/).selectOption('venue');
    await page.getByRole('button', { name: 'Search', exact: true }).click();
    check('Venue search shows location filters and identity', await page.getByLabel('City (optional)', { exact: true }).isVisible() && await results().getByText('1 Main Street, Boston').first().isVisible());
    check('Locationless venue search is explicit', await results().getByText('Location not supplied', { exact: true }).isVisible());
    await results().getByRole('button', { name: /^Follow Private venue with/ }).click();
    check('Locationless venue collection is explicit', await collection().getByText('Location not supplied', { exact: true }).isVisible());
    await collection().getByRole('button', { name: /^Unfollow Private venue with/ }).click();
    check('Locationless venue can be removed', await collection().locator('li').count() === 1);
    await results().getByRole('button', { name: 'Follow Private venue', exact: true }).click();
    check('Artist/venue same ID stay distinct', await collection().locator('li').count() === 2);
    await capture('desktop', 1440);
    await capture('tablet', 1024);
    await capture('mobile', 390);
    await capture('320', 320);
    await capture('200-text', 390, true);
    await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
    await page.emulateMedia({ reducedMotion: 'reduce', forcedColors: 'active' });
    await page.getByLabel('Name', { exact: true }).focus();
    await page.keyboard.press('Tab');
    check('Keyboard reaches venue location field', await page.evaluate(() => document.activeElement.id === 'follow-city'));
    check('Forced colors/reduced motion retain focus outline', await page.getByLabel('City (optional)', { exact: true }).evaluate(node => getComputedStyle(node).outlineStyle !== 'none'));
    await page.emulateMedia({ reducedMotion: 'no-preference', forcedColors: 'none' });
    await page.goto(base + '/me');
    await page.locator('main').getByRole('link', { name: 'Follows', exact: true }).click();
    check('Compact profile reaches follows', await collection().locator('li').count() === 2);
    const secondSession = await browser.newContext({ javaScriptEnabled: false });
    await secondSession.addCookies([{ name: 'ticketopia_session', value: process.env.FOLLOWS_SESSION, url: base }]);
    const native = await secondSession.newPage();
    await native.goto(base + '/follows');
    check('New browser session retains follows without JS', await native.locator('ul[aria-label="Your follows"] li').count() === 2);
    await native.getByRole('button', { name: 'Unfollow Private artist', exact: true }).click();
    check('No-JS Unfollow removes one kind only', await native.locator('ul[aria-label="Your follows"] li').count() === 1);
    await page.goto(fallback + '/follows?kind=venue&keyword=Uncached');
    check('Provider outage preserves follows with search error', await page.getByText('Search couldn\'t load', { exact: true }).isVisible() && await collection().locator('li').count() === 1);
    await capture('outage', 390);
    await collection().getByRole('button', { name: 'Unfollow Private venue', exact: true }).click();
    check('Provider-free Unfollow succeeds', await collection().count() === 0);
    await page.goto(base + '/follows?kind=artist&keyword=Private');
    await results().getByRole('button', { name: 'Follow Private artist', exact: true }).click();
    const secondFollow = await api('PUT', '/api/v1/me/follows/venue/ticketmaster:Follow_0');
    check('API creates follow from retained metadata', secondFollow.status() === 201);
    await page.goto(base + '/follows?limit=1');
    check('Collection paginates', await collection().locator('li').count() === 1 && await page.getByRole('link', { name: 'More follows', exact: true }).isVisible());
    await page.getByRole('link', { name: 'More follows', exact: true }).click();
    check('Collection second page', await collection().locator('li').count() === 1 && !await page.getByRole('link', { name: 'More follows', exact: true }).isVisible());
    await page.goto(base + '/follows?filter=venue');
    check('Kind filter', await collection().locator('li').count() === 1 && await collection().getByText('Venue', { exact: true }).isVisible());
    await page.goto(base + '/follows?kind=artist&keyword=Pages');
    await page.getByRole('link', { name: 'More search results', exact: true }).click();
    check('Search paginates independently', await results().locator('li').count() === 1 && new URL(page.url()).searchParams.has('search_cursor'));
    await page.goto(base + '/follows?kind=artist&keyword=Nothing');
    check('Honest empty search', await page.getByText('No matches found.', { exact: false }).isVisible());
    const guest = await browser.newContext(); const guestPage = await guest.newPage();
    await guestPage.goto(base + '/follows');
    check('Guest must sign in with task return', guestPage.url().includes('/auth/sign-in?return_to='));
    const other = await browser.newContext();
    await other.addCookies([{ name: 'ticketopia_session', value: process.env.FOLLOWS_OTHER_SESSION, url: base }]);
    const otherPage = await other.newPage(); await otherPage.goto(base + '/follows');
    check('Other owner cannot see follows', await otherPage.locator('ul[aria-label="Your follows"]').count() === 0);
    const blocked = await owner.request.put(base + '/api/v1/me/follows/artist/ticketmaster:Follow_0');
    check('Cookie API mutation requires CSRF', blocked.status() === 403);
    const forbidden = await owner.request.post(base + '/follows/artist/ticketmaster:Follow_0', { form: { action: 'unfollow', return_to: '/follows', csrf_token: 'bad' } });
    check('Native invalid CSRF rejects write with recovery', forbidden.status() === 403 && (await forbidden.text()).includes('Return to your follows'));
    const touch = await browser.newContext({ hasTouch: true, viewport: { width: 390, height: 844 } });
    await touch.addCookies([{ name: 'ticketopia_session', value: process.env.FOLLOWS_SESSION, url: base }]);
    const touchPage = await touch.newPage();
    await touchPage.goto(base + '/follows?kind=artist&keyword=Private');
    await touchPage.locator('ul[aria-label="Search results"]').getByRole('button', { name: /^Follow Private artist with/ }).tap();
    await touchPage.locator('ul[aria-label="Your follows"]').getByRole('button', { name: /^Unfollow Private artist with/ }).waitFor({ state: 'visible' });
    check('Touch Follow succeeds', await touchPage.locator('ul[aria-label="Your follows"]').getByRole('button', { name: /^Unfollow Private artist with/ }).isVisible());
    await touchPage.locator('ul[aria-label="Your follows"]').getByRole('button', { name: /^Unfollow Private artist with/ }).tap();
    await touchPage.locator('ul[aria-label="Search results"]').getByRole('button', { name: /^Follow Private artist with/ }).waitFor({ state: 'visible' });
    check('Touch Unfollow succeeds', await touchPage.locator('ul[aria-label="Your follows"]').getByRole('button', { name: /^Unfollow Private artist with/ }).count() === 0);
    await guestPage.goto(process.env.FOLLOWS_DISABLED_URL + '/follows');
    check('Disabled accounts explained', await guestPage.getByText('Following requires accounts', { exact: false }).isVisible());
    check('No browser runtime errors', report.consoleErrors.length === 0);
    await browser.close();
    fs.writeFileSync(path.join(out, 'follows-checks.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify({ checks: report.checks.length, accessibility: report.accessibility.length, screenshots: report.screenshots }));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
