// Isolated SQL/provider fixtures with production auth and CSRF. See docs/event-interest.md.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.SAVED_BASE_URL;
const out = path.resolve(__dirname, '../.impeccable/review');
const report = { checks: [], screenshots: [], accessibility: [], consoleErrors: [] };
const check = (name, result) => { assert.ok(result, name); report.checks.push(name); };
fs.mkdirSync(out, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE });
  try {
    const owner = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await owner.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_FIXTURE_TOKEN, url: base }]);
    const page = await owner.newPage();
    page.on('pageerror', error => report.consoleErrors.push(error.message));
    const guest = await browser.newContext();
    const other = await browser.newContext();
    await other.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_OTHER_TOKEN, url: base }]);
    const me = await (await owner.request.get(base + '/api/v1/me')).json();
    const otherMe = await (await other.request.get(base + '/api/v1/me')).json();
    const id = 'ticketmaster:Browser_0';
    const set = async (context, csrf, eventID, data = {}) => {
      const response = await context.request.put(base + '/api/v1/me/event-interests/' + eventID, { data, headers: { 'X-CSRF-Token': csrf } });
      check('Authenticated PUT ' + eventID, response.ok()); return response.json();
    };
    const list = async () => (await owner.request.get(base + '/api/v1/me/event-interests')).json();
    const participants = async () => (await guest.request.get(base + '/api/v1/events/' + id + '/interested-users')).json();
    const capture = async (name, width, zoom = false) => {
      if (process.env.PARTICIPATION_SKIP_CAPTURES === 'true') return;
      await page.setViewportSize({ width, height: 1000 });
      await page.evaluate(async zoom => { document.documentElement.style.fontSize = zoom ? '200%' : ''; await document.fonts.ready; scrollTo(0, 0); }, zoom);
      check('No overflow: ' + name, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      check('44px interest targets: ' + name, await page.locator('.interest-button:visible').evaluateAll(buttons => buttons.every(button => button.getBoundingClientRect().height >= 44)));
      check('Open editors sit below the aggregate, not beside it: ' + name, await page.locator('[data-interest-privacy][open]').evaluateAll(editors => editors.every(editor => editor.getBoundingClientRect().top >= editor.parentElement.querySelector('[data-interest-count]').getBoundingClientRect().bottom)));
      const file = path.join(out, name + '.png'); await page.screenshot({ path: file, fullPage: true }); report.screenshots.push(file);
      if (process.env.AXE_SCRIPT) {
        await page.addScriptTag({ path: process.env.AXE_SCRIPT });
        const violations = await page.evaluate(async () => (await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] } })).violations);
        report.accessibility.push({ name, violations }); check('Accessibility: ' + name, !violations.length);
      }
    };
    await page.goto(base + '/me/interests');
    check('Own empty interest and private category preferences remain distinct', await page.getByRole('heading', { name: "Events you're interested in" }).count() === 1 && await page.getByRole('button', { name: 'Save category preferences' }).count() === 1);
    await page.goto(base + process.env.SAVED_SEARCH_PATH);
    await page.locator('.event-link').first().click();
    const context = page.locator('[data-context-id="' + id + '"]');
    await context.waitFor();
    await context.locator('.context-event-details > summary').click();
    check('New choices visibly disclose Private', await context.locator('.interest-button').innerText() === 'Interested · Private');
    check('Accessible action name includes its visible label', (await context.locator('.interest-button').getAttribute('aria-label')).includes(await context.locator('.interest-button').innerText()));
    let release; let started;
    const pending = new Promise(resolve => { release = resolve; });
    const observed = new Promise(resolve => { started = resolve; });
    await page.route('**/interests/' + id, async route => { started(); await pending; await route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ detail: 'Interest is temporarily unavailable. Try again.' }) }); });
    await context.locator('.interest-button').click(); await observed;
    check('Pending controls synchronize row and preview', await page.locator('[data-interest-form][aria-busy="true"]').count() === 4);
    release();
    await context.getByRole('alert').filter({ hasText: 'temporarily unavailable' }).waitFor();
    check('Failed writes retain choice and allow retry', await context.locator('.interest-button').getAttribute('aria-pressed') === 'false' && await context.locator('.interest-button').isEnabled() && !(await list()).items.length);
    check('Only one actionable error is visible', await page.locator('[data-interest-feedback]:visible').count() === 1);
    await capture('interest-error-desktop', 1440);
    await context.getByRole('button', { name: 'Dismiss', exact: true }).click();
    check('Dismissing errors clears them and returns focus to the action', await page.locator('[data-interest-feedback]:visible').count() === 0 && await context.locator('.interest-button').evaluate(node => node === document.activeElement));
    await context.locator('.interest-button').click();
    await context.getByRole('alert').filter({ hasText: 'temporarily unavailable' }).waitFor();
    await page.unroute('**/interests/' + id);
    await context.locator('.interest-button').click();
    await page.waitForFunction(() => [...document.querySelectorAll('.interest-button')].filter(button => button.getAttribute('aria-pressed') === 'true').length === 2);
    check('Selected state synchronizes independently of count', await page.locator('[data-interest-count="' + id + '"]').first().innerText() === '1 person interested');
    check('Success updates controls without lingering feedback', await page.locator('[data-interest-feedback]:visible').count() === 0);
    check('Privacy has one state label and a closed editor', await context.locator('[data-interest-privacy]').evaluate(node => !node.open) && await context.locator('summary').filter({ hasText: 'Change visibility' }).count() === 1 && !await context.getByText('Interest visibility:').count());
    check('Aggregate number is emphasized separately', await context.locator('[data-interest-count] strong').innerText() === '1');
    check('Private choice has no public participant identity', !(await participants()).items.length);
    const save = await owner.request.put(base + '/api/v1/me/saved-events/' + id, { headers: { 'X-CSRF-Token': me.csrf_token } });
    check('Saving remains independent', save.ok() && (await list()).items.length === 1);
    const privacy = context.locator('[data-interest-privacy]');
    await page.locator('.event-row [data-interest-privacy] summary').first().click();
    await privacy.locator('summary').click(); await privacy.locator('select').selectOption('public');
    check('Only one visibility editor opens at a time', await page.locator('[data-interest-privacy][open]').count() === 1);
    // A failed edit keeps the unsaved selection available without duplicating errors.
    await page.route('**/interests/' + id, route => route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ detail: 'Visibility could not be saved. Try again.' }) }));
    await privacy.getByRole('button', { name: 'Save visibility' }).click();
    await privacy.getByRole('alert').waitFor();
    check('Failed visibility edits remain open with the last confirmed action', await privacy.evaluate(node => node.open) && await privacy.locator('select').inputValue() === 'public' && await context.locator('.interest-button').innerText() === 'Interested · Private');
    await page.locator('.event-row .interest-button').first().click();
    await page.locator('.event-row [data-interest-feedback]:visible').waitFor();
    check('A new failed action replaces the previous error instead of accumulating', await page.locator('[data-interest-feedback]:visible').count() === 1 && !await privacy.locator('[data-interest-feedback]').isVisible());
    await page.unroute('**/interests/' + id);
    await privacy.getByRole('button', { name: 'Save visibility' }).click();
    await page.waitForFunction(() => document.querySelector('[data-context-id] .interest-button span')?.textContent === 'Interested · Public');
    check('Saving visibility closes the editor and returns focus to its summary', await privacy.evaluate(node => !node.open && node.querySelector('summary') === document.activeElement));
    check('Success clears old errors throughout the page', await page.locator('[data-interest-feedback]:visible').count() === 0);
    check('Explicit public visibility discloses only public projection', (await participants()).items[0].profile.id === process.env.SAVED_FIXTURE_ID && !JSON.stringify(await participants()).includes(me.item.email));
    await context.getByRole('link', { name: 'Community', exact: true }).click();
    await context.locator('[data-public-participants] a[href="/users/' + process.env.SAVED_FIXTURE_ID + '"]').waitFor();
    check('Public participants are reachable in event community section', true);
    await set(other, otherMe.csrf_token, id);
    const count = await (await guest.request.get(base + '/api/v1/events/' + id + '/interest')).json();
    check('Public count includes private interest without identities', count.count === 2 && Object.keys(count).length === 1 && (await participants()).items.length === 1);
    await set(other, otherMe.csrf_token, id, { visibility: 'public' });
    await set(owner, me.csrf_token, 'ticketmaster:Browser_2', { visibility: 'private' });
    const ownFirstPage = await (await owner.request.get(base + '/api/v1/me/event-interests?limit=1')).json();
    const origin = '/me/interests?limit=1&cursor=' + encodeURIComponent(ownFirstPage.next_cursor);
    await page.goto(base + '/events/' + id + '/interested-users?limit=1&return_to=' + encodeURIComponent(origin));
    await page.getByRole('link', { name: 'More public participants' }).click();
    check('Participant pagination retains the originating collection cursor', new URL(page.url()).searchParams.get('return_to') === origin);
    await page.getByRole('link', { name: 'Back to event' }).click();
    check('Participant Back to event restores collection return context', new URL(page.url()).searchParams.get('return_to') === origin);
    await page.getByRole('link', { name: 'Back to Interests' }).click();
    check('Return to original interest page works after participant pagination', new URL(page.url()).pathname + new URL(page.url()).search === origin);
    await owner.request.delete(base + '/api/v1/me/event-interests/ticketmaster:Browser_2', { headers: { 'X-CSRF-Token': me.csrf_token } });
    await set(other, otherMe.csrf_token, id, { visibility: 'private' });
    await page.goto(base + process.env.SAVED_SEARCH_PATH + '&selected_event=' + encodeURIComponent(id) + '&section=community');
    await context.locator('.context-event-details > summary').click();
    await owner.request.patch(base + '/api/v1/me/profile', { data: { interest_visibility: 'public' }, headers: { 'X-CSRF-Token': me.csrf_token } });
    const fresh = await set(owner, me.csrf_token, 'ticketmaster:Browser_1');
    check('Profile default applies to new choices', fresh.visibility === 'public');
    await context.locator('[data-interest-privacy] summary').click();
    await context.locator('[data-interest-privacy] select').selectOption('private');
    await context.getByRole('button', { name: 'Save visibility' }).click();
    await page.locator('[data-interest-status]').filter({ hasText: 'Interest saved as private.' }).waitFor({ state: 'attached' });
    await page.waitForFunction(() => !document.querySelector('[data-public-participants] a'));
    check('Enhanced action name still includes its visible label', (await context.locator('.interest-button').getAttribute('aria-label')).includes(await context.locator('.interest-button').innerText()));
    check('Privacy revocation removes identity from the current community panel', !(await participants()).items.length);
    const publicPage = await guest.newPage(); await publicPage.goto(base + '/users/' + process.env.SAVED_FIXTURE_ID);
    check('Public profile includes only public event interest', !await publicPage.getByRole('link', { name: 'A good night in the city', exact: true }).count() && await publicPage.locator('.public-interest-list li').count() === 1);
    await page.goto(base + '/me/interests?limit=1');
    check('Own interest collection is paginated', await page.locator('.event-row').count() === 1 && await page.getByRole('link', { name: 'More interested events' }).count() === 1);
    await page.getByRole('link', { name: 'More interested events' }).click();
    await page.locator('.event-link').click();
    check('Event retains interest collection return cursor', await page.getByRole('link', { name: 'Back to Interests' }).count() === 1);
    await page.getByRole('link', { name: 'Back to Interests' }).click();
    await page.locator('.interest-button').click();
    await page.waitForLoadState('networkidle');
    check('Removing interest does not remove bookmark', (await owner.request.get(base + '/api/v1/me/saved-events/' + id)).status() === 200);
    // Restore the private choice and inspect the complete event UI once at all sizes.
    await set(owner, me.csrf_token, id, { visibility: 'private' });
    await page.goto(base + '/events/' + id + '?section=community');
    await capture('interest-event-compact-desktop', 1440);
    await capture('interest-event-compact-mobile', 390);
    await page.locator('[data-interest-privacy] summary').click();
    await capture('interest-event-desktop', 1440);
    await capture('interest-event-tablet', 1024);
    await capture('interest-event-mobile', 390);
    await capture('interest-event-320', 320);
    await capture('interest-event-200-text', 390, true);
    await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto(base + '/me/interests'); await capture('interest-collection-desktop', 1440); await capture('interest-collection-mobile', 390);
    // Native form writes do not use JavaScript and return to the same event.
    const native = await browser.newContext({ javaScriptEnabled: false });
    await native.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_FIXTURE_TOKEN, url: base }]);
    const nativePage = await native.newPage(); await nativePage.goto(base + '/events/' + id);
    await nativePage.locator('.interest-button').click();
    check('Native remove returns to event', nativePage.url() === base + '/events/' + id && await nativePage.locator('.interest-button').getAttribute('aria-pressed') === 'false');
    await nativePage.locator('.interest-button').click();
    check('Native new choice discloses the public account default', await nativePage.locator('.interest-button').innerText() === 'Interested · Public');
    await nativePage.locator('[data-interest-privacy] summary').click();
    await nativePage.locator('[data-interest-privacy] select').selectOption('private');
    await nativePage.getByRole('button', { name: 'Save visibility' }).click();
    check('Native visibility change returns with a compact confirmed control', await nativePage.locator('.interest-button').innerText() === 'Interested · Private' && await nativePage.locator('[data-interest-privacy]').evaluate(node => !node.open));
    const sourceFree = await owner.request.get(process.env.SAVED_FALLBACK_URL + '/events/' + id);
    check('Interest metadata survives provider/cache loss', sourceFree.status() === 200 && (await sourceFree.text()).includes('Showing last-known details'));
    await publicPage.goto(process.env.SAVED_DISABLED_URL + '/events/' + id);
    check('Disabled accounts do not fabricate counts or successful actions', !await publicPage.locator('[data-interest-count]').count() && await publicPage.getByRole('button', { name: 'Interested', exact: true }).isDisabled());
    const unauthorized = await guest.request.put(base + '/api/v1/me/event-interests/' + id, { data: {} });
    check('Guest writes rejected', unauthorized.status() === 401);
    check('No browser runtime errors', report.consoleErrors.length === 0);
  } finally {
    await browser.close();
    fs.writeFileSync(path.join(out, 'interest-checks.json'), JSON.stringify(report, null, 2));
  }
  console.log(JSON.stringify({ checks: report.checks.length, accessibility: report.accessibility.length, screenshots: report.screenshots.length }));
})().catch(error => { console.error(error); process.exitCode = 1; });
