// Isolated SQL/provider accounts with production auth/CSRF. See docs/event-recommendations.md.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.SAVED_BASE_URL;
const out = path.resolve(__dirname, '../.impeccable/review');
const report = { checks: [], screenshots: [], accessibility: [], consoleErrors: [] };
const check = (name, result) => { assert.ok(result, name); report.checks.push(name); };
fs.mkdirSync(out, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE });
  try {
    const owner = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await owner.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_FIXTURE_TOKEN, url: base }]);
    const other = await browser.newContext();
    await other.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_OTHER_TOKEN, url: base }]);
    const guest = await browser.newContext();
    const me = await (await owner.request.get(base + '/api/v1/me')).json();
    const otherMe = await (await other.request.get(base + '/api/v1/me')).json();
    const page = await owner.newPage();
    page.on('pageerror', error => report.consoleErrors.push(error.message));
    const id = 'ticketmaster:Browser_0';
    const endpoint = '/api/v1/me/event-recommendations/' + id;
    const own = async () => (await owner.request.get(base + endpoint)).json();
    const eventList = async () => (await guest.request.get(base + '/api/v1/events/' + id + '/recommendations')).json();
    const capture = async (name, width, zoom = false) => {
      await page.setViewportSize({ width, height: 1000 });
      await page.evaluate(async zoom => { document.documentElement.style.fontSize = zoom ? '200%' : ''; await document.fonts.ready; scrollTo(0, 0); }, zoom);
      const overflow = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, nodes: [...document.querySelectorAll('main *')].filter(node => node.getBoundingClientRect().right > innerWidth + 1).map(node => ({ tag: node.tagName, classes: node.className, text: node.textContent.slice(0, 80), width: node.getBoundingClientRect().width })) }));
      if (overflow.scrollWidth > overflow.width) console.error(JSON.stringify(overflow));
      check('No horizontal overflow: ' + name, overflow.scrollWidth <= overflow.width);
      check('44px recommendation action targets: ' + name, await page.locator('.recommendation-editor summary:visible, [data-recommendation-form] button:visible, .community-page .recommendation-event .text-link:visible').evaluateAll(nodes => nodes.every(node => node.getBoundingClientRect().height >= 44)));
      const file = path.join(out, name + '.png'); await page.screenshot({ path: file, fullPage: true }); report.screenshots.push(file);
      if (process.env.AXE_SCRIPT) {
        await page.addScriptTag({ path: process.env.AXE_SCRIPT });
        const violations = await page.evaluate(async () => (await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] } })).violations);
        report.accessibility.push({ name, violations }); check('Accessibility: ' + name, !violations.length);
      }
    };
    check('Private save fixture', (await owner.request.put(base + '/api/v1/me/saved-events/' + id, { headers: { 'X-CSRF-Token': me.csrf_token } })).ok());
    check('Private interest fixture', (await owner.request.put(base + '/api/v1/me/event-interests/' + id, { data: { visibility: 'private' }, headers: { 'X-CSRF-Token': me.csrf_token } })).ok());
    await page.goto(base + process.env.SAVED_SEARCH_PATH);
    await page.locator('.event-link').first().click();
    const context = page.locator('[data-context-id="' + id + '"]');
    await context.waitFor();
    await context.getByRole('link', { name: 'Recommend', exact: true }).click();
    const panel = context.locator('[data-event-recommendations]');
    await panel.waitFor();
    check('Secondary Recommend directly opens and focuses composer', await panel.locator('details').evaluate(node => node.open && node.querySelector('textarea') === document.activeElement));
    check('Public attribution is disclosed before publishing', (await panel.innerText()).includes('Interest privacy does not hide recommendations.'));
    const draft = 'Worth seeing live. A useful perspective for a first visit.';
    await panel.locator('textarea').fill(draft);
    let release; let started;
    const pending = new Promise(resolve => { release = resolve; });
    const observed = new Promise(resolve => { started = resolve; });
    await page.route('**/recommendations/' + id, async route => { started(); await pending; await route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ detail: 'Recommendation storage is unavailable. Try again.' }) }); });
    await panel.getByRole('button', { name: 'Publish recommendation' }).click(); await observed;
    check('Pending submission disables mutation controls', await panel.locator('form').getAttribute('aria-busy') === 'true' && await panel.locator('textarea').isDisabled());
    release(); await panel.locator('[data-recommendation-error]').waitFor({ state: 'visible' });
    check('Failure keeps draft and confirmed public state', await panel.locator('textarea').inputValue() === draft && (await eventList()).count === 0 && await panel.locator('textarea').isEnabled());
    await capture('recommendation-error-desktop', 1440);
    await page.unroute('**/recommendations/' + id);
    await panel.getByRole('button', { name: 'Publish recommendation' }).click();
    await panel.locator('.recommendation-reason').filter({ hasText: draft }).waitFor();
    const first = await own();
    check('Publishing refreshes public attribution without replacing results', (await eventList()).count === 1 && await page.locator('.event-row').count() === 2 && new URL(page.url()).searchParams.get('selected_event') === id);
    check('Success closes composer and restores focus', await panel.locator('details').evaluate(node => !node.open && node.querySelector('summary') === document.activeElement));
    await panel.locator('summary').click();
    const edited = 'Bring a friend and enjoy the atmosphere.';
    await panel.locator('textarea').fill(edited);
    await context.getByRole('link', { name: 'Overview', exact: true }).click();
    await context.getByRole('link', { name: 'Community', exact: true }).click();
    await panel.locator('textarea').waitFor({ state: 'visible' });
    check('Draft survives section navigation', await panel.locator('textarea').inputValue() === edited);
    await page.setViewportSize({ width: 390, height: 900 });
    check('Draft survives mobile resize with event identity', await panel.locator('textarea').inputValue() === edited && await context.locator('h2').first().innerText() === 'A good night in the city');
    await panel.getByRole('button', { name: 'Save recommendation' }).click();
    await panel.locator('.recommendation-reason').filter({ hasText: edited }).waitFor();
    check('Editing keeps publication ordering', (await own()).recommended_at === first.recommended_at && (await own()).reason === edited);
    check('Recommend did not change Save or private Interested', (await owner.request.get(base + '/api/v1/me/saved-events/' + id)).status() === 200 && (await (await owner.request.get(base + '/api/v1/me/event-interests/' + id)).json()).visibility === 'private');
    const guestPage = await guest.newPage();
    await guestPage.goto(base + '/events/' + id + '?section=community');
    check('Guest can browse and is invited to sign in, not publish', await guestPage.getByText(edited, { exact: true }).count() === 1 && await guestPage.getByRole('link', { name: 'Sign in to recommend' }).count() === 1 && !await guestPage.locator('[data-public-participants] a').count());
    await guestPage.goto(base + '/users/' + process.env.SAVED_FIXTURE_ID);
    check('Public recommendation appears independently of private interest', await guestPage.getByText(edited, { exact: true }).count() === 1 && !await guestPage.locator('.public-interest-list li').count());
    check('API exposes no private account data', !JSON.stringify(await eventList()).includes(me.item.email));
    check('Other user can independently endorse the same event', (await other.request.put(base + endpoint, { data: { reason: 'A second public perspective.' }, headers: { 'X-CSRF-Token': otherMe.csrf_token } })).status() === 201);
    check('Public count means explicit recommendations', (await eventList()).count === 2 && (await eventList()).items.length === 2);
    check('Second event endorsement fixture', (await owner.request.put(base + '/api/v1/me/event-recommendations/ticketmaster:Browser_1', { data: { reason: 'Another event worth sharing.' }, headers: { 'X-CSRF-Token': me.csrf_token } })).status() === 201);
    const grouped = async () => (await guest.request.get(base + '/api/v1/community/recommendations?city=Berlin')).json();
    const originalGroup = (await grouped()).items.find(item => item.event.id === id);
    check('Grouped API has one event entry with both named reasons', (await grouped()).items.length === 2 && originalGroup.count === 2 && originalGroup.recommendations.length === 2);
    check('Compatible individual API still exposes each endorsement', (await (await guest.request.get(base + '/api/v1/recommendations')).json()).items.length === 3);
    for (const [context, csrf] of [[owner, me.csrf_token], [other, otherMe.csrf_token]]) {
      check('Withdraw for anti-bump check', (await context.request.delete(base + endpoint, { headers: { 'X-CSRF-Token': csrf } })).status() === 204);
    }
    check('Event disappears only when no active endorsements remain', (await grouped()).items.length === 1 && (await eventList()).count === 0);
    check('Owner republication is a reactivation', (await owner.request.put(base + endpoint, { data: { reason: edited }, headers: { 'X-CSRF-Token': me.csrf_token } })).status() === 201);
    check('Other republication is a reactivation', (await other.request.put(base + endpoint, { data: { reason: 'A second public perspective.' }, headers: { 'X-CSRF-Token': otherMe.csrf_token } })).status() === 201);
    check('All-withdrawn republication preserves event and endorsement ordering', (await own()).recommended_at === first.recommended_at && (await grouped()).items[0].event.id === 'ticketmaster:Browser_1' && (await grouped()).items[1].first_recommended_at === originalGroup.first_recommended_at);
    await page.goto(base + '/community?city=Berlin&category_id=sports');
    check('Community renders one entry per event with both named reasons', await page.locator('.recommendation-event').count() === 2 && await page.locator('.community-recommenders li').count() === 3 && await page.getByText('A second public perspective.', { exact: true }).count() === 1);
    await page.goto(base + '/community?city=Berlin&category_id=sports&limit=1');
    check('City/category feed is public and paginated', await page.locator('.recommendation-event').count() === 1 && await page.getByRole('link', { name: 'More recommendations' }).count() === 1);
    await page.getByRole('link', { name: 'More recommendations' }).click();
    const origin = new URL(page.url()).pathname + new URL(page.url()).search;
    await page.getByRole('link', { name: 'See all recommendations for this event' }).click();
    check('Grouped full-list link retains filtered feed context', new URL(page.url()).searchParams.get('return_to') === origin && await page.locator('.recommendation-list > li').count() === 2);
    await page.getByRole('link', { name: 'Back to event' }).click();
    await page.getByRole('link', { name: 'Back to Community' }).click();
    await page.locator('.recommendation-event h3 a').click();
    check('Community event link retains filtered cursor return', new URL(page.url()).searchParams.get('return_to') === origin);
    await page.getByRole('link', { name: 'Back to Community' }).click();
    check('Back returns to same community page', new URL(page.url()).pathname + new URL(page.url()).search === origin);
    await page.goto(base + '/events/' + id + '/recommendations?limit=1&return_to=' + encodeURIComponent(origin));
    await page.getByRole('link', { name: 'More recommendations' }).click();
    check('Event endorsement pagination preserves origin', new URL(page.url()).searchParams.get('return_to') === origin);
    await page.getByRole('link', { name: 'Back to event' }).click();
    check('Event endorsement Back retains community context', new URL(page.url()).searchParams.get('return_to') === origin);
    await page.goto(base + '/community?city=Chicago');
    check('Empty filtered recommendations provide guidance', !await page.locator('.recommendation-event').count() && await page.getByText('No recommendations on this page.', { exact: false }).count() === 1);
    // Native forms: explicit publication, editing, optional reason, and withdrawal.
    const native = await browser.newContext({ javaScriptEnabled: false });
    await native.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_FIXTURE_TOKEN, url: base }]);
    const nativePage = await native.newPage();
    await nativePage.goto(base + '/events/' + id);
    await nativePage.getByRole('link', { name: 'Recommend', exact: true }).click();
    check('Native Recommend directly opens composer', await nativePage.locator('.recommendation-editor').getAttribute('open') !== null);
    await nativePage.locator('[data-recommendation-form] textarea').fill('Preserved native recovery reason.');
    await nativePage.locator('[data-recommendation-form] input[name="csrf_token"]').evaluate(node => { node.value = 'expired'; });
    await nativePage.getByRole('button', { name: 'Save recommendation' }).click();
    check('Native CSRF rejection keeps draft and safe destination', await nativePage.locator('textarea').inputValue() === 'Preserved native recovery reason.' && await nativePage.getByRole('link', { name: 'Back to event' }).count() === 1 && (await own()).reason === edited);
    await nativePage.getByRole('button', { name: 'Retry recommendation' }).click();
    check('Native CSRF recovery retries with verified current credential', (await own()).reason === 'Preserved native recovery reason.');
    await nativePage.goto(base + '/events/' + id + '?section=community');
    await nativePage.locator('.recommendation-editor summary').click();
    await nativePage.locator('[data-recommendation-form] textarea').fill('Retained after session expiry.');
    await native.clearCookies();
    await nativePage.getByRole('button', { name: 'Save recommendation' }).click();
    check('Native session expiry retains draft with sign-in/event recovery', await nativePage.locator('textarea').inputValue() === 'Retained after session expiry.' && await nativePage.getByRole('link', { name: 'Sign in to continue' }).count() === 1 && await nativePage.getByRole('link', { name: 'Back to event' }).count() === 1 && (await own()).reason === 'Preserved native recovery reason.');
    await native.addCookies([{ name: 'ticketopia_session', value: process.env.SAVED_FIXTURE_TOKEN, url: base }]);
    await nativePage.goto(base + '/events/' + id + '?section=community&return_to=' + encodeURIComponent(origin));
    await nativePage.locator('.recommendation-editor summary').click();
    await nativePage.getByRole('button', { name: 'Withdraw recommendation' }).click();
    check('Native withdrawal returns with origin and removes only own endorsement', new URL(nativePage.url()).searchParams.get('return_to') === origin && (await eventList()).count === 1);
    await nativePage.locator('.recommendation-editor summary').click();
    await nativePage.getByRole('button', { name: 'Publish recommendation' }).click();
    check('Native form supports optional empty reason', (await own()).reason === '' && (await eventList()).count === 2);
    await nativePage.locator('.recommendation-editor summary').click(); await nativePage.locator('[data-recommendation-form] textarea').fill('A native form reason.');
    await nativePage.getByRole('button', { name: 'Save recommendation' }).click();
    check('Native edit works without JavaScript', (await own()).reason === 'A native form reason.');
    check('Private saved and interest choices survive native withdrawal', (await owner.request.get(base + '/api/v1/me/saved-events/' + id)).status() === 200 && (await owner.request.get(base + '/api/v1/me/event-interests/' + id)).status() === 200);
    // An additional endorsement exercises independently paginated profile activity.
    check('Second event identical retry remains a replacement', (await owner.request.put(base + '/api/v1/me/event-recommendations/ticketmaster:Browser_1', { data: { reason: 'Another event worth sharing.' }, headers: { 'X-CSRF-Token': me.csrf_token } })).status() === 200);
    await page.goto(base + '/users/' + process.env.SAVED_FIXTURE_ID + '?limit=1');
    await page.getByRole('link', { name: 'More public recommendations' }).click();
    check('Profile endorsements paginate separately from interest', new URL(page.url()).searchParams.has('recommendation_cursor') && !new URL(page.url()).searchParams.has('cursor') && await page.locator('.recommendation-event').count() === 1);
    await page.locator('.recommendation-event h3 a').click();
    check('Profile-to-event return remains available', await page.getByRole('link', { name: 'Back to profile' }).count() === 1);
    await page.goto(process.env.SAVED_FALLBACK_URL + '/events/' + id + '?section=community');
    check('Provider/cache outage keeps event and published reasons', await page.locator('.recommendation-reason').filter({ hasText: 'A native form reason.' }).count() === 1 && await page.getByText('Showing last-known details.', { exact: false }).count() > 0);
    await page.goto(process.env.SAVED_DISABLED_URL + '/community');
    check('Disabled account deployment is truthful', (await page.innerText('main')).includes('require accounts to be enabled'));
    const disabled = await guest.request.get(process.env.SAVED_DISABLED_URL + '/api/v1/recommendations');
    check('Disabled API does not fabricate empty activity', disabled.status() === 503);
    await page.goto(base + '/community?city=Berlin');
    await capture('recommendation-community-desktop', 1440); await capture('recommendation-community-mobile', 390);
    await capture('recommendation-community-tablet', 1024); await capture('recommendation-community-320', 320); await capture('recommendation-community-200-text', 390, true);
    await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
    await page.goto(base + '/events/' + id + '?section=community');
    await page.locator('.recommendation-editor summary').click();
    await capture('recommendation-event-desktop', 1440); await capture('recommendation-event-tablet', 1024);
    await capture('recommendation-event-mobile', 390); await capture('recommendation-event-320', 320); await capture('recommendation-event-200-text', 390, true);
    check('No runtime errors', report.consoleErrors.length === 0);
    fs.writeFileSync(path.join(out, 'recommendation-checks.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify({ checks: report.checks.length, screenshots: report.screenshots.length, accessibility: report.accessibility.length }));
  } finally { await browser.close(); }
})().catch(error => { fs.writeFileSync(path.join(out, 'recommendation-checks.json'), JSON.stringify({ ...report, error: error.stack }, null, 2)); console.error(error); process.exitCode = 1; });
